'use client';
import { usePathname } from 'next/navigation';
import {
  YoutubeFilled,
  FacebookFilled,
  TwitchFilled,
  InstagramFilled,
  LinkedinFilled
} from '@ant-design/icons';
import styles from './Footer.module.css';
import Image from 'next/image';
import Link from 'next/link';
import { Button, Card, Col, Row, Form, Input, Collapse, Divider } from 'antd';

const Footer = () => {
  const pathname = usePathname();
  const currentYear = new Date().getFullYear();

  // Don't show the footer on the chat route
  if (pathname === '/chat') {
    return null;
  }

  return (
    <>
      {/* FAQs */}
      <section id="faqs" className={styles.faqContainer}>
        <h2 style={{ textAlign: 'center', marginBottom: 24 }}>
          Frequently Asked <span className={styles.highlight}>Questions</span>
        </h2>

        <div style={{ maxWidth: 700, margin: '0 auto' }}>
          <Collapse
            accordion
            bordered={false}
            expandIconPosition="right"
            style={{ backgroundColor: 'transparent' }}
            items={[
              {
                key: '1',
                label: 'What is the AI Tools Website?',
                children: (
                  <p>
                    The AI Tools Website offers a collection of advanced AI tools,
                    including YouTube, text, PDF, and Word file summarizers, as well
                    as an interactive chatbot, to assist users with content analysis
                    and information extraction.
                  </p>
                ),
              },
              ...[
                'How do I use the YouTube video summarizer?',
                'Can the text summarizer handle large documents?',
                'How accurate is the PDF summarizer?',
                'What types of Word files can I upload for summarization?',
                'Can the chatbot answer specific questions based on uploaded documents?',
                'Do I need to create an account to use the AI tools?',
                'Can I download the summaries generated by the tools?',
                'How secure is my data when I upload files for summarization?',
              ].map((q, idx) => ({
                key: (idx + 2).toString(),
                label: q,
                children: <p>This is a placeholder answer for: {q}</p>,
              })),
            ]}
          />
        </div>
      </section>

      {/* Contact Us Form */}
      <section id="contact" className={styles.contact}>
        <h2 style={{ textAlign: 'center', marginBottom: 8 }}>
          Send Us <span className={styles.highlight}>A Message</span>
        </h2>

        <div
          style={{
            maxWidth: 600,
            margin: '20px auto',
            padding: 24,
            border: '1px solid #f0f0f0',
            borderRadius: 8,
            boxShadow: '0 0 0 rgba(0,0,0,0)',
            backgroundColor: '#fff',
          }}
        >
          <Form layout="vertical">
            <Row gutter={16}>
              <Col span={12}>
                <Form.Item label="Name">
                  <Input placeholder="Enter your Full Name" />
                </Form.Item>
              </Col>
              <Col span={12}>
                <Form.Item label="Mobile Number">
                  <Input placeholder="Enter your Mobile Number" />
                </Form.Item>
              </Col>
            </Row>
            <Form.Item label="Email">
              <Input placeholder="Enter your Email" />
            </Form.Item>
            <Form.Item label="Message">
              <Input.TextArea rows={4} placeholder="Enter your message" />
            </Form.Item>
            <Form.Item>
              <Button
                type="primary"
                block
                style={{
                  background: 'linear-gradient(to right, #4f46e5, #9333ea)',
                  border: 'none',
                }}
              >
                Send Message
              </Button>
            </Form.Item>
          </Form>
        </div>
      </section>


    <footer className={styles.footer}>
      <div className={styles.grid}>
        {/* Logo and Description */}
        <div className={styles.column}>
          <Image src="/assets/Logo.svg" alt="Logo" width={52} height={52} />
          {/* <h3 className={styles.brand}>IntelliTools</h3> */}
          <p className={styles.description}>
              Discover intelligent solutions to simplify tasks,<br /> enhance creativity, and save time — built for <br /> professionals, creators, and teams.
          </p>
          <div className={styles.socialIcons}>
            <FacebookFilled />
            <TwitchFilled />
            <InstagramFilled />
            <LinkedinFilled />
            <YoutubeFilled />
          </div>
        </div>

        {/* Our Tools */}
        <div className={styles.column}>
          <h3 className={styles.heading}>Our Tools</h3>
          <ul className={styles.linkList}>
            <li><Link href="/youtube">AI YouTube Summarizer</Link></li>
            {/* <li><Link href="/pdf">AI PDF Summarizer</Link></li> */}
            <li><Link href="/word">AI Word Summarizer</Link></li>
            <li><Link href="/text">AI Text Summarizer</Link></li>
            <li><Link href="/chat">AI Chatbot</Link></li>
          </ul>
        </div>


        {/* Contact Info */}
        <div className={styles.column}>
          <h3 className={styles.heading}>Contact Us</h3>
          <p className={styles.text}>📧 contact@company.com</p>
          <p className={styles.text}>📞 (414) 687 - 5892</p>
          <p className={styles.text}>
            📍 794 Mcallister St<br />San Francisco, 94102
          </p>
        </div>
      </div>

      {/* Footer Bottom */}
      <hr/>
      <div className={styles.bottom}>
        <p>Copyright &copy; {currentYear} IntelliTools. </p>
        <div className={styles.links}>
          <a href="#">All rights reserved</a> | <a href="#">Terms & Conditions</a> | <a href="#">Privacy Policy</a>
        </div>
      </div>
      </footer>
      </>
  );
};

export default Footer;
